Fixes CVE-2020-20907.
Desc:
  In Lib/tarfile.py in Python through 3.8.3, an attacker is able to craft a TAR
  archive leading to an infinite loop when opened by tarfile.open, because
  _proc_pax lacks header validation.

Upstream bug: https://bugs.python.org/issue39017

Backported from upstream commit:
https://github.com/python/cpython/commit/5a8d121a1f3ef5ad7c105ee378cc79a3eac0c7d4

--- Python-2.7.18/Lib/tarfile.py
+++ Python-2.7.18/Lib/tarfile.py
@@ -1400,6 +1400,8 @@ class TarInfo(object):
 
             length, keyword = match.groups()
             length = int(length)
+            if length == 0:
+                raise InvalidHeaderError("invalid header")
             value = buf[match.end(2) + 1:match.start(1) + length - 1]
 
             keyword = keyword.decode("utf8")
